flags: {}
packages:
- '.'
- location:
    git: git://github.com/mtolly/midi
    commit: 28866f4715cde594d8d8ec5e6f3beecb64783614
  extra-dep: true
extra-deps:
- conduit-audio-0.2.0.3
- midi-util-0.2.0.1
- conduit-audio-samplerate-0.1.0.3
resolver: lts-12.2
